version: '2.1'
networks:
  rabbitmq.localnet:
    driver: bridge
services:
  rabbitmq:
    build: ./rabbitmq
    networks: [ rabbitmq.localnet ]
    ports:
    - '5672:5672'
    - '15672:15672'
#    volumes:
#    - 'rabbitmq.data:/bitnami'
#volumes:
#  rabbitmq.data:
#    driver: local
