version: '3.7'
networks:
  mysql.localnet:
volumes:
  mysql.data:
services:
  mysql:
    image: mysql:8.0
    networks: [ mysql.localnet ]
    volumes: [ mysql.data:/var/lib/mysql ]
    command: 
      - '--default-authentication-plugin=mysql_native_password'
      - '--character-set-server=utf8'
    environment:
      MYSQL_ROOT_PASSWORD: root123!
    ports: ['3306:3306']
  adminer_container:
    image: adminer:4.8.0-standalone
    networks: [ mysql.localnet ]
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports: [8090:8080]
