version: '3.7'
networks:
  mysql.localnet:
services:
  adminer_container:
    image: adminer:4.8.0-standalone
    networks: [ mysql.localnet ]
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports: [8090:8080]
  mysql:
    build: ./mysql
    networks: [ mysql.localnet ]
    ports: ['3306:3306']
    #volumes: [ mysql.data:/var/lib/mysql ]
#volumes:
#  mysql.data:
